name: Claats

on:
  push:
    branches:
      - main

jobs:
  claats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install claats
        run: |
          curl -L -o /usr/local/bin/claats https://github.com/ShawnLabo/claats/releases/download/v0.1.4/claats_0.1.4_Linux_x86_64
          chmod +x /usr/local/bin/claats
      - name: Run claats
        run: |
          claats -pattern "**/LAB.md" -title "ShawnLabo - Google Cloud Tutorials" -ga UA-191798031-4
      - name: Commit
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m ":robot: Auto claats at `date --iso-8601=seconds`"
          git push origin main

